name = "uploader-fix"
main = "src/index.js"
account_id = "9e9500d1925c42f12f71e04cda1a1c98"
compatibility_date = "2025-07-26"
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "wedding-uploads"

[vars]
R2_ACCESS_KEY_ID = "d70f16fb96e8b93d2530fffa162ac07c"
R2_SECRET_ACCESS_KEY = "52eb8165acc2b3a3bfcd13e295eed361b3877af537a0a2236fc1379065b2d5a9"
