name = "worker"
main = "worker.js"
compatibility_date = "2024-07-27"

[vars]
R2_BUCKET_NAME = "wedding-uploads"
R2_ENDPOINT = "https://s3.eu-central-003.backblazeb2.com"
R2_REGION = "eu-central-003"

r2_buckets = [
  { binding = "R2_BUCKET", bucket_name = "wedding-uploads" }
]

[observability.logs]
enabled = true

